export default function getAllProducts() {
  return [
    {
      id: "CBC-CO-001",
      slug: "triple-choco-chunk-cookies",
      name: "Triple Choco Chunk",
      category: "Cookies",
      categorySlug: "cookies",
      price: 20_000,
      stock: 100,
      imageUrl: "/assets/images/cookies-1.jpg",
      description: `Experience the perfect balance of textures and flavors with our Triple Choco Chunk Cookies. Packed with generous chunks of dark, milk, and white chocolate, these cookies are crispy on the outside and deliciously chewy on the inside. A true treat for chocolate lovers!.`,
    },
    {
      id: "CBC-BR-002",
      slug: "fudge-fantasy-brownie",
      name: "Fudge Fantasy",
      category: "Brownie",
      categorySlug: "brownie",
      price: 35_000,
      stock: 5,
      imageUrl: `/assets/images/brownie-1.jpg`,
      description: `Delight in the rich, decadent taste of our Fudgy Fantasy Brownie. With a moist and gooey center, this brownie is made for those who crave intense chocolate flavor. Topped with a smooth chocolate glaze, it's a dessert you won’t forget.`,
    },
    {
      id: "CBC-CA-003",
      slug: "chocolate-symphony-cake",
      name: "Chocolate Symphony",
      category: "Cake",
      categorySlug: "cake",
      price: 280_000,
      stock: 0,
      imageUrl: `/assets/images/birthday-cake-1.jpg`,
      description: `Celebrate in elegance with our Chocolate Symphony Cake. This cake features layers of moist chocolate sponge and creamy ganache, finished with a glossy chocolate glaze. Perfectly crafted for chocolate enthusiasts and special moments alike!.`,
    },
    {
      id: "CBC-CO-004",
      slug: "golden-crunch-delight-cookies",
      name: "Golden Crunch Delight",
      category: "Cookies",
      categorySlug: "cookies",
      price: 25_000,
      stock: 30,
      imageUrl: `/assets/images/cookies-2.jpg`,
      description: `Savor the delightful crunch of our Golden Crunch Delight Cookies. Made with golden-brown buttery dough, a hint of caramel, and crispy cereal flakes, these cookies are the perfect balance of sweet and crunchy. Each bite is a golden moment of bliss!`,
    },
    {
      id: "CBC-BR-005",
      slug: "chewy-choco-craze-brownie",
      name: "Chewy Choco Craze",
      category: "Brownie",
      categorySlug: "brownie",
      price: 30_000,
      stock: 30,
      imageUrl: `/assets/images/brownie-2.jpg`,
      description: `Indulge in the rich decadence of our Chewy Choco Craze Brownie. Packed with gooey chocolate chunks and a perfectly chewy texture, this brownie delivers a burst of intense chocolate flavor in every bite. A must-try for true chocolate lovers!`,
    },
    {
      id: "CBC-CA-006",
      slug: "rainbow-cake-sparkle-cake",
      name: "Rainbow Cake Sparkle",
      category: "Cake",
      categorySlug: "cake",
      price: 300_000,
      stock: 5,
      imageUrl: `/assets/images/birthday-cake-2.jpg`,
      description: `Celebrate in vibrant style with our Rainbow Sparkle Cake. Featuring moist, colorful layers of vanilla sponge, topped with creamy frosting and shimmering edible sparkles, this cake is as joyful as it is delicious. Perfect for special occasions or just spreading happiness!`,
    },
    {
      id: "CBC-CO-007",
      slug: "double-trouble-chocolate-cookies",
      name: "Double Trouble Chocolate",
      category: "Cookies",
      categorySlug: "cookies",
      price: 20_000,
      stock: 30,
      imageUrl: `/assets/images/cookies-3.jpg`,
      description: `Dive into double the chocolate goodness with our Double Trouble Chocolate Cookies. Each cookie is loaded with rich cocoa and studded with dark and milk chocolate chunks, offering an irresistible mix of chewy and melty textures. Perfect for chocoholics craving an intense treat!.`,
    },
    {
      id: "CBC-BR-008",
      slug: "raspberry-cocoa-fantasy-brownie",
      name: "Raspberry Cocoa Fantasy",
      category: "Brownie",
      categorySlug: "brownie",
      price: 35_000,
      stock: 0,
      imageUrl: `/assets/images/brownie-3.jpg`,
      description: `A harmonious blend of tangy and sweet, the Raspberry Choco Fantasy Brownie combines rich, fudgy chocolate with bursts of raspberry flavor. Topped with a drizzle of raspberry glaze, this brownie is a decadent escape for your taste buds.`,
    },
    {
      id: "CBC-CA-009",
      slug: "almond-bliss-cake",
      name: "Almond Bliss Cake",
      category: "Cake",
      categorySlug: "cake",
      price: 350_000,
      stock: 2,
      imageUrl: `/assets/images/cake-3.jpg`,
      description: `Delight in the elegant simplicity of our Almond Bliss Cake. Featuring moist almond-infused sponge layers, creamy almond frosting, and a topping of toasted almond slices, this cake delivers a nutty, buttery flavor perfect for any occasion.`,
    },
    {
      id: "CBC-CO-010",
      slug: "monster-cookie-cookies",
      name: "Monster Cookie",
      category: "Cookies",
      categorySlug: "cookies",
      price: 30_000,
      stock: 15,
      imageUrl: `/assets/images/cookies-4.jpg`,
      description: `Unleash your inner cookie monster with our Monster Cookie Cookies! Bursting with chocolate chips, colorful candy-coated chocolates, oats, and a hint of peanut butter, these cookies are big, bold, and packed with a monstrous amount of flavor.`,
    },
    {
      id: "CBC-BR-011",
      slug: "caramel-swirl-delight-brownie",
      name: "Caramel Swirl Delight",
      category: "Brownie",
      categorySlug: "brownie",
      price: 25_000,
      stock: 10,
      imageUrl: `/assets/images/brownie-4.jpg`,
      description: `Experience pure indulgence with our Caramel Swirl Delight Brownie. This rich, fudgy brownie is swirled with luscious caramel and baked to perfection, creating a dreamy combination of chocolate and caramel in every bite.`,
    },
    {
      id: "CBC-CA-012",
      slug: "cheese-slice-cake-cake",
      name: "Cheese Slice Cake",
      category: "Cake",
      categorySlug: "cake",
      price: 50_000,
      stock: 0,
      imageUrl: `/assets/images/cake-4.jpg`,
      description: `A classic favorite, the Cheese Slice Cake features smooth, creamy cheesecake on a buttery graham cracker crust. Each slice is light, rich, and perfectly sweetened—a timeless dessert for any occasion.A classic favorite, the Cheese Slice Cake features smooth, creamy cheesecake on a buttery graham cracker crust. Each slice is light, rich, and perfectly sweetened—a timeless dessert for any occasion.`,
    },
  ];
}
